name: Comet Contribution Graph

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: kiaquila/comet-contribution-graph@v1
        with:
          username: ish-g09
          reduced: "true"
